# Generated by Django 3.2.4 on 2021-08-19 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_category', models.CharField(max_length=50)),
                ('device_sales', models.CharField(max_length=20)),
                ('device_year', models.CharField(max_length=20)),
            ],
        ),
    ]
